### ISSUE TITLE
Segmentation loop and zipfile issue

### ISSUE THREAD

**Issue by CameronBodine** [dbuscombe-usgs/dash_doodler#54]
I'm getting strange behavior with the latest Doodler version. After segmenting an image, I try to open another image, but the pull down menu for selecting a new image is blank, despite there still being images to segment. When I switch back to the `Imagery and Controls` tab, the blue cube is spinning. When I had this error, I noticed the command prompt was throwing an error about invalid values in the `rescale` function in the `image_segmentation.py`, line 66 in the doodler engine. So I added a print statement (`print(dat, mn, mx, m, M)`) to print the values, and re-launched Doodler. It appears that Doodler is getting caught in a loop during segmentation (see output below). Then there is also an issue zipping the outputs (see below). Any thoughts?

```
(base) PS C:\Users\bodin> conda activate dashdoodler
(dashdoodler) PS C:\Users\bodin> cd .\Python\dash_doodler\
(dashdoodler) PS C:\Users\bodin\Python\dash_doodler> python .\doodler.py
Hyperparameters imported from my_defaults.py
Go to http://127.0.0.1:8050/ in your web browser to use Doodler
Dash is running on http://127.0.0.1:8050/

 * Serving Flask app 'app'
 * Debug mode: off
[[-1.72921586 -1.72921586 -1.72921586 ... -1.72921586 -1.72921586
  -1.72921586]
 [-1.72921586 -1.72921586 -1.72921586 ... -1.72921586 -1.72921586
  -1.72921586]
 [-1.72921586 -1.72921586 -1.72921586 ... -1.72921586 -1.72921586
  -1.72921586]
 ...
 [-1.72921586 -1.71262034 -1.72921586 ... -1.29773242 -1.33092345
  -1.36411449]
 [-1.72921586 -1.71262034 -1.72921586 ... -1.49687862 -1.43049656
  -1.38071001]
 [-1.72921586 -1.69602482 -1.72921586 ... -1.72921586 -1.72921586
  -1.72921586]] 0 1 -1.729215858471188 2.4362588616589593
my_defaults.py overwritten with parameter settings
[[-1.72921586 -1.72921586 -1.72921586 ... -1.72921586 -1.72921586
  -1.72921586]
 [-1.72921586 -1.72921586 -1.72921586 ... -1.72921586 -1.72921586
  -1.72921586]
 [-1.72921586 -1.72921586 -1.72921586 ... -1.72921586 -1.72921586
  -1.72921586]
 ...
 [-1.72921586 -1.71262034 -1.72921586 ... -1.29773242 -1.33092345
  -1.36411449]
 [-1.72921586 -1.71262034 -1.72921586 ... -1.49687862 -1.43049656
  -1.38071001]
 [-1.72921586 -1.69602482 -1.72921586 ... -1.72921586 -1.72921586
  -1.72921586]] 0 1 -1.729215858471188 2.4362588616589593
[[-1.72921586 -1.72921586 -1.72921586 ... -1.72921586 -1.72921586
  -1.72921586]
 [-1.72921586 -1.72921586 -1.72921586 ... -1.72921586 -1.72921586
  -1.72921586]
 [-1.72921586 -1.72921586 -1.72921586 ... -1.72921586 -1.72921586
  -1.72921586]
 ...
 [-1.72921586 -1.71262034 -1.72921586 ... -1.29773242 -1.33092345
  -1.36411449]
 [-1.72921586 -1.71262034 -1.72921586 ... -1.49687862 -1.43049656
  -1.38071001]
 [-1.72921586 -1.69602482 -1.72921586 ... -1.72921586 -1.72921586
  -1.72921586]] 0 1 -1.729215858471188 2.4362588616589593
[[-1.72921586 -1.72921586 -1.72921586 ... -1.72921586 -1.72921586
  -1.72921586]
 [-1.72921586 -1.72921586 -1.72921586 ... -1.72921586 -1.72921586
  -1.72921586]
 [-1.72921586 -1.72921586 -1.72921586 ... -1.72921586 -1.72921586
  -1.72921586]
 ...
 [-1.72921586 -1.71262034 -1.72921586 ... -1.29773242 -1.33092345
  -1.36411449]
 [-1.72921586 -1.71262034 -1.72921586 ... -1.49687862 -1.43049656
  -1.38071001]
 [-1.72921586 -1.69602482 -1.72921586 ... -1.72921586 -1.72921586
  -1.72921586]] 0 1 -1.729215858471188 2.4362588616589593
[[-1.72921586 -1.72921586 -1.72921586 ... -1.72921586 -1.72921586
  -1.72921586]
 [-1.72921586 -1.72921586 -1.72921586 ... -1.72921586 -1.72921586
  -1.72921586]
 [-1.72921586 -1.72921586 -1.72921586 ... -1.72921586 -1.72921586
  -1.72921586]
 ...
 [-1.72921586 -1.71262034 -1.72921586 ... -1.29773242 -1.33092345
  -1.36411449]
 [-1.72921586 -1.71262034 -1.72921586 ... -1.49687862 -1.43049656
  -1.38071001]
 [-1.72921586 -1.69602482 -1.72921586 ... -1.72921586 -1.72921586
  -1.72921586]] 0 1 -1.729215858471188 2.4362588616589593
[[-1.72921586 -1.72921586 -1.72921586 ... -1.72921586 -1.72921586
  -1.72921586]
 [-1.72921586 -1.72921586 -1.72921586 ... -1.72921586 -1.72921586
  -1.72921586]
 [-1.72921586 -1.72921586 -1.72921586 ... -1.72921586 -1.72921586
  -1.72921586]
 ...
 [-1.72921586 -1.71262034 -1.72921586 ... -1.29773242 -1.33092345
  -1.36411449]
 [-1.72921586 -1.71262034 -1.72921586 ... -1.49687862 -1.43049656
  -1.38071001]
 [-1.72921586 -1.69602482 -1.72921586 ... -1.72921586 -1.72921586
  -1.72921586]] 0 1 -1.729215858471188 2.4362588616589593
[[-1.72921586 -1.72921586 -1.72921586 ... -1.72921586 -1.72921586
  -1.72921586]
 [-1.72921586 -1.72921586 -1.72921586 ... -1.72921586 -1.72921586
  -1.72921586]
 [-1.72921586 -1.72921586 -1.72921586 ... -1.72921586 -1.72921586
  -1.72921586]
 ...
 [-1.72921586 -1.71262034 -1.72921586 ... -1.29773242 -1.33092345
  -1.36411449]
 [-1.72921586 -1.71262034 -1.72921586 ... -1.49687862 -1.43049656
  -1.38071001]
 [-1.72921586 -1.69602482 -1.72921586 ... -1.72921586 -1.72921586
  -1.72921586]] 0 1 -1.729215858471188 2.4362588616589593
Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "C:\Users\bodin\miniconda3\envs\dashdoodler\lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\bodin\miniconda3\envs\dashdoodler\lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\bodin\miniconda3\envs\dashdoodler\lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\bodin\miniconda3\envs\dashdoodler\lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\bodin\miniconda3\envs\dashdoodler\lib\site-packages\dash\dash.py", line 1274, in dispatch
    ctx.run(
  File "C:\Users\bodin\miniconda3\envs\dashdoodler\lib\site-packages\dash\_callback.py", line 440, in add_context
    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%
  File "C:\Users\bodin\Python\dash_doodler\app.py", line 850, in update_output
    tmp = saved_data[k]
  File "C:\Users\bodin\miniconda3\envs\dashdoodler\lib\site-packages\numpy\lib\npyio.py", line 242, in __getitem__
    bytes = self.zip.open(key)
  File "C:\Users\bodin\miniconda3\envs\dashdoodler\lib\zipfile.py", line 1532, in open
    raise BadZipFile("Truncated file header")
zipfile.BadZipFile: Truncated file header
Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "C:\Users\bodin\miniconda3\envs\dashdoodler\lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\bodin\miniconda3\envs\dashdoodler\lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\bodin\miniconda3\envs\dashdoodler\lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\bodin\miniconda3\envs\dashdoodler\lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\bodin\miniconda3\envs\dashdoodler\lib\site-packages\dash\dash.py", line 1274, in dispatch
    ctx.run(
  File "C:\Users\bodin\miniconda3\envs\dashdoodler\lib\site-packages\dash\_callback.py", line 440, in add_context
    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%
  File "C:\Users\bodin\Python\dash_doodler\app.py", line 847, in update_output
    saved_data = np.load(numpyfile)
  File "C:\Users\bodin\miniconda3\envs\dashdoodler\lib\site-packages\numpy\lib\npyio.py", line 422, in load
    ret = NpzFile(fid, own_fid=own_fid, allow_pickle=allow_pickle,
  File "C:\Users\bodin\miniconda3\envs\dashdoodler\lib\site-packages\numpy\lib\npyio.py", line 178, in __init__
    _zip = zipfile_factory(fid)
  File "C:\Users\bodin\miniconda3\envs\dashdoodler\lib\site-packages\numpy\lib\npyio.py", line 101, in zipfile_factory
    return zipfile.ZipFile(file, *args, **kwargs)
  File "C:\Users\bodin\miniconda3\envs\dashdoodler\lib\zipfile.py", line 1269, in __init__
    self._RealGetContents()
  File "C:\Users\bodin\miniconda3\envs\dashdoodler\lib\zipfile.py", line 1336, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
[[-1.72921586 -1.72921586 -1.72921586 ... -1.72921586 -1.72921586
  -1.72921586]
 [-1.72921586 -1.72921586 -1.72921586 ... -1.72921586 -1.72921586
  -1.72921586]
 [-1.72921586 -1.72921586 -1.72921586 ... -1.72921586 -1.72921586
  -1.72921586]
 ...
 [-1.72921586 -1.71262034 -1.72921586 ... -1.29773242 -1.33092345
  -1.36411449]
 [-1.72921586 -1.71262034 -1.72921586 ... -1.49687862 -1.43049656
  -1.38071001]
 [-1.72921586 -1.69602482 -1.72921586 ... -1.72921586 -1.72921586
  -1.72921586]] 0 1 -1.729215858471188 2.4362588616589593
[[-1.72921586 -1.72921586 -1.72921586 ... -1.72921586 -1.72921586
  -1.72921586]
 [-1.72921586 -1.72921586 -1.72921586 ... -1.72921586 -1.72921586
  -1.72921586]
 [-1.72921586 -1.72921586 -1.72921586 ... -1.72921586 -1.72921586
  -1.72921586]
 ...
 [-1.72921586 -1.71262034 -1.72921586 ... -1.29773242 -1.33092345
  -1.36411449]
 [-1.72921586 -1.71262034 -1.72921586 ... -1.49687862 -1.43049656
  -1.38071001]
 [-1.72921586 -1.69602482 -1.72921586 ... -1.72921586 -1.72921586
  -1.72921586]] 0 1 -1.729215858471188 2.4362588616589593
my_defaults.py overwritten with parameter settings
my_defaults.py overwritten with parameter settings
[[-1.72921586 -1.72921586 -1.72921586 ... -1.72921586 -1.72921586
  -1.72921586]
 [-1.72921586 -1.72921586 -1.72921586 ... -1.72921586 -1.72921586
  -1.72921586]
 [-1.72921586 -1.72921586 -1.72921586 ... -1.72921586 -1.72921586
  -1.72921586]
 ...
 [-1.72921586 -1.71262034 -1.72921586 ... -1.29773242 -1.33092345
  -1.36411449]
 [-1.72921586 -1.71262034 -1.72921586 ... -1.49687862 -1.43049656
  -1.38071001]
 [-1.72921586 -1.69602482 -1.72921586 ... -1.72921586 -1.72921586
  -1.72921586]] 0 1 -1.729215858471188 2.4362588616589593
[[-1.72921586 -1.72921586 -1.72921586 ... -1.72921586 -1.72921586
  -1.72921586]
 [-1.72921586 -1.72921586 -1.72921586 ... -1.72921586 -1.72921586
  -1.72921586]
 [-1.72921586 -1.72921586 -1.72921586 ... -1.72921586 -1.72921586
  -1.72921586]
 ...
 [-1.72921586 -1.71262034 -1.72921586 ... -1.29773242 -1.33092345
  -1.36411449]
 [-1.72921586 -1.71262034 -1.72921586 ... -1.49687862 -1.43049656
  -1.38071001]
 [-1.72921586 -1.69602482 -1.72921586 ... -1.72921586 -1.72921586
  -1.72921586]] 0 1 -1.729215858471188 2.4362588616589593
Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "C:\Users\bodin\miniconda3\envs\dashdoodler\lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\bodin\miniconda3\envs\dashdoodler\lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\bodin\miniconda3\envs\dashdoodler\lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\bodin\miniconda3\envs\dashdoodler\lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\bodin\miniconda3\envs\dashdoodler\lib\site-packages\dash\dash.py", line 1274, in dispatch
    ctx.run(
  File "C:\Users\bodin\miniconda3\envs\dashdoodler\lib\site-packages\dash\_callback.py", line 440, in add_context
    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%
  File "C:\Users\bodin\Python\dash_doodler\app.py", line 850, in update_output
    tmp = saved_data[k]
  File "C:\Users\bodin\miniconda3\envs\dashdoodler\lib\site-packages\numpy\lib\npyio.py", line 243, in __getitem__
    return format.read_array(bytes,
  File "C:\Users\bodin\miniconda3\envs\dashdoodler\lib\site-packages\numpy\lib\format.py", line 778, in read_array
    data = _read_bytes(fp, read_size, "array data")
  File "C:\Users\bodin\miniconda3\envs\dashdoodler\lib\site-packages\numpy\lib\format.py", line 907, in _read_bytes
    r = fp.read(size - len(data))
  File "C:\Users\bodin\miniconda3\envs\dashdoodler\lib\zipfile.py", line 940, in read
    data = self._read1(n)
  File "C:\Users\bodin\miniconda3\envs\dashdoodler\lib\zipfile.py", line 1008, in _read1
    data += self._read2(n - len(data))
  File "C:\Users\bodin\miniconda3\envs\dashdoodler\lib\zipfile.py", line 1043, in _read2
    raise EOFError
EOFError
```

**Comment by CameronBodine** [comment]
Also, the results folder has multiple labels even though I only hit the segmentation button once..

**Comment by ddbuscombe** [comment]
- [ ] is your doodler-engine up to date?
- [ ] are you using the recommended firefox browser?
- [ ] please provide your log file
- [ ] please provide an image and a classes.txt so we can reproduce

**Comment by CameronBodine** [comment]
- `doodler_engine==0.0.3`
- Yes, using firefox
- [Log File](https://drive.google.com/file/d/1pklfw3hkii6L1VWRLZNZkLIW4i_6pqZd/view?usp=share_link)
- [Examples which caused error](https://drive.google.com/drive/folders/1eI7_uyF58FuOZZ_vIfZlvkU5uVlMGlnU?usp=share_link)

Thanks!

**Comment by ddbuscombe** [comment]
Thanks, I shall take a :eyes:

**Comment by CameronBodine** [comment]
It seems to fix the issue if I deselect `Compute/Show segmentation` before changing to the `File List and Instructions` tab. I will update if I see the problem happen again.

**Comment by ddbuscombe** [comment]
Deselecting the `compute/show segmentation` before proceeding to the next tab is generally recommended. I also notice that you are loading a LOT of images into your assets folder. That is probably slowing the program down because it has so many files to search through to cross-check against the labeled folder. I would recommend just loading the number of images you can anticipate completing in a single session.

**Comment by CameronBodine** [comment]
That sounds good. I have been having much more success doodling today, following deselection of segmentation.  Good to know on # of images in assets folder.  Will give that a try too. Thanks!

**Comment by CameronBodine** [comment]
I can confirm that the following helps remedy the issues I was seeing:

- Decrease the number of images in the `assets` folder. I aim for around 20 images and the software is snappier overall.
- Deselect `compute/show segmentation` before switching to the `file list and instructions` tab to select a new image.

I will go ahead and close the issue as these steps remedy the issue.
